listenAddress: "0.0.0.0:8989"
endpoints:
  - path: /fullBackup
    command: echo
    args:
    - hello
    - world
    - -lala
  - path: /sleep
    allowMulti: true
    command: /bin/sh
    args: 
    - -c
    - "for i in {1..60};do echo hello $(date);sleep 1;done"
  - path: /quick
    command: /bin/sh
    args: 
    - -c
    - "for i in {1..30};do [[ $(($i%5)) -eq 0 ]] && { echo error >&2 ; } || { echo hello $(date); }; sleep 0.2;done"
  - path: /error
    command: /bin/sh
    args: 
    - -c
    - "sleep 5;"
