FROM alpine as builder

RUN apk add --no-cache --update ca-certificates

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY build/linux/rexecutor /usr/bin/rexecutor
ENTRYPOINT ["/usr/bin/rexecutor"]
CMD ["-c","config.yaml"]